# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Cockos.REAPER
PackageVersion: "7.32"
Platform:
- Windows.Desktop
MinimumOSVersion: 5.1.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
InstallerSuccessCodes:
- 1223
UpgradeBehavior: install
ProductCode: REAPER
AppsAndFeaturesEntries:
- DisplayName: REAPER
Installers:
- Architecture: x86
  InstallerUrl: https://www.reaper.fm/files/7.x/reaper732-install.exe
  InstallerSha256: 3189EDFEB519C2F95FBC443781A07B2E73739B65B6539097955D669268FBBA68
- Architecture: x64
  InstallerUrl: https://www.reaper.fm/files/7.x/reaper732_x64-install.exe
  InstallerSha256: CFC93E51211CDE12D70FF5749D30EC53EA5A575043973DB03A4190AA377829F7
- Architecture: arm64
  InstallerUrl: https://www.reaper.fm/files/7.x/reaper732_win11_arm64ec_beta-install.exe
  InstallerSha256: B75B56A15FC2AA459BFB58C940D8C80ED40A5463970DFBE1AF283FECCBCFBFB0
ManifestType: installer
ManifestVersion: 1.9.0
