# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Cockos.REAPER
PackageVersion: "7.31"
Platform:
- Windows.Desktop
MinimumOSVersion: 5.1.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
InstallerSuccessCodes:
- 1223
UpgradeBehavior: install
ProductCode: REAPER
AppsAndFeaturesEntries:
- DisplayName: REAPER
Installers:
- Architecture: x86
  InstallerUrl: https://www.reaper.fm/files/7.x/reaper731-install.exe
  InstallerSha256: 6F6A1A8D910332882218C72A977ABAD9EC85A465EC5E1538E1D82F7317F0AD36
- Architecture: x64
  InstallerUrl: https://www.reaper.fm/files/7.x/reaper731_x64-install.exe
  InstallerSha256: 3A02C91F703D2D8DA8476D0333B9A3610A754D617ECA538C906BC0F8343849FA
- Architecture: arm64
  InstallerUrl: https://www.reaper.fm/files/7.x/reaper731_win11_arm64ec_beta-install.exe
  InstallerSha256: 575D735D86235366EA80A51C14DD734E8A64DE4C53DD50657315EA8EE3BE29BB
ManifestType: installer
ManifestVersion: 1.9.0
